# Generated by Django 3.1.7 on 2022-12-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.CharField(choices=[('Free', 'FREE'), ('Ocupied', 'OCUPIED')], default='True', max_length=20)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='capstone.parking')),
            ],
        ),
    ]
