# Generated by Django 3.1.7 on 2022-12-17 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0002_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slot',
            old_name='available',
            new_name='status',
        ),
    ]
