# Generated by Django 3.1.7 on 2022-12-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0003_auto_20221217_1751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
