# Generated by Django 3.1.7 on 2022-12-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0007_auto_20221220_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='parks_created',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='times_parked',
            field=models.IntegerField(default=0),
        ),
    ]
