# Generated by Django 3.1.7 on 2022-12-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0008_auto_20221220_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='category',
            field=models.CharField(choices=[('car', 'CAR'), ('motorcycle', 'MOTORCYCLE'), ('car_motorcycle', 'CAR_MOTORCYCLE')], default='car', max_length=20),
        ),
    ]
