# Generated by Django 3.1.7 on 2022-12-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0009_auto_20221220_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='category',
            field=models.CharField(choices=[('car', 'CAR'), ('motorcycle', 'MOTORCYCLE'), ('both', 'BOTH')], default='car', max_length=20),
        ),
    ]
