# Generated by Django 3.1.7 on 2022-12-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0010_auto_20221220_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='creator',
            field=models.CharField(default='unknown', max_length=140),
        ),
    ]
