# Generated by Django 3.1.7 on 2022-12-20 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0011_parking_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loghistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
