# Generated by Django 3.1.7 on 2022-12-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0012_loghistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loghistory',
            name='id',
        ),
        migrations.AddField(
            model_name='loghistory',
            name='logid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
