# Generated by Django 3.1.7 on 2022-12-20 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0013_auto_20221220_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parks_created',
        ),
        migrations.RemoveField(
            model_name='user',
            name='times_logged',
        ),
        migrations.RemoveField(
            model_name='user',
            name='times_parked',
        ),
        migrations.CreateModel(
            name='Parkhistory',
            fields=[
                ('logid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_parked', to='capstone.parking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_parked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Createparkhistory',
            fields=[
                ('logid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='park_creaed', to='capstone.parking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
