# Generated by Django 3.1.7 on 2022-12-23 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0014_auto_20221220_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('logid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_that_is_being_parked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_who_is_parking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
