# Generated by Django 3.1.7 on 2022-12-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0016_remove_park_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='parking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_that_is_being_parked', to='capstone.parking'),
        ),
    ]
