# Generated by Django 3.1.7 on 2022-12-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0017_auto_20221223_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='category',
            field=models.CharField(default='unknown', max_length=15),
        ),
        migrations.AddField(
            model_name='park',
            name='licensePlate',
            field=models.CharField(default='aaaa0000', max_length=8),
        ),
    ]
