# Generated by Django 3.1.7 on 2022-12-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0018_auto_20221223_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loghistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
