# Generated by Django 3.1.7 on 2022-12-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0019_auto_20221224_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createparkhistory',
            name='date',
            field=models.CharField(default='UNAVAILABLE DATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='loghistory',
            name='date',
            field=models.CharField(default='UNAVAILABLE DATE', max_length=30),
        ),
        migrations.AlterField(
            model_name='parkhistory',
            name='date',
            field=models.CharField(default='UNAVAILABLE DATE', max_length=30),
        ),
    ]
