# Generated by Django 3.1.7 on 2022-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0020_auto_20221224_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='address',
            field=models.CharField(default='unknown', max_length=280),
        ),
    ]
